import type { CollectionName } from '../../shared/types';
import type { FormField } from '../components/LocalizedForm';
import * as pagesService from '../services/pages.service';
import * as servicesService from '../services/services.service';
import * as partnersService from '../services/partners.service';
import * as industriesService from '../services/industries.service';
import * as caseStudiesService from '../services/caseStudies.service';
import * as blogPostsService from '../services/blogPosts.service';
import * as insightEventsService from '../services/insightEvents.service';
import * as insightLabsService from '../services/insightLabs.service';
import * as jobsService from '../services/jobs.service';
import * as teamMembersService from '../services/teamMembers.service';
import * as homeSectionsService from '../services/homeSections.service';
import * as serviceCategoriesService from '../services/serviceCategories.service';
import * as blogCategoriesService from '../services/blogCategories.service';
import * as resourcesService from '../services/resources.service';
import * as testimonialsService from '../services/testimonials.service';

export interface CollectionConfig {
  collectionName: CollectionName;
  title: string;
  singularTitle: string;
  basePath: string;
  emptyMessage: string;
  fields: FormField[];
  getAll: () => Promise<any[]>;
  getById: (id: string) => Promise<any | null>;
  create: (payload: any) => Promise<any>;
  update: (id: string, payload: any) => Promise<any>;
  remove: (id: string) => Promise<void>;
  toFormValues: (item?: any | null) => Record<string, any>;
  fromFormValues: (values: Record<string, any>, current?: any | null) => Record<string, any>;
}

function serializeCsv(value: any) {
  return Array.isArray(value) ? value.join(', ') : '';
}

function parseCsv(value: string) {
  return (value || '')
    .split(/[\n,]/)
    .map((entry) => entry.trim())
    .filter(Boolean);
}

function serializeJson(value: any) {
  if (value === null || value === undefined || value === '') return '';
  return JSON.stringify(value, null, 2);
}

function parseJson(value: string, fallback: any) {
  if (!value?.trim()) return fallback;
  try {
    return JSON.parse(value);
  } catch {
    throw new Error('El contenido JSON no tiene un formato válido.');
  }
}

function serializeLines(value: any) {
  return Array.isArray(value) ? value.join('\n') : '';
}

function parseLines(value: string) {
  return (value || '')
    .split('\n')
    .map((entry) => entry.trim())
    .filter(Boolean);
}

function normalizeMediaPath(value: any) {
  if (typeof value !== 'string') return value || null;
  const trimmed = value.trim();
  if (!trimmed) return null;
  if (
    trimmed.startsWith('/assets/') ||
    trimmed.startsWith('http://') ||
    trimmed.startsWith('https://') ||
    trimmed.startsWith('data:')
  ) {
    return trimmed;
  }
  if (trimmed.startsWith('assets/')) {
    return `/${trimmed}`;
  }
  return trimmed;
}

function serializeSeoValue(value: any, key: 'metaTitle' | 'metaDescription') {
  if (!value || typeof value !== 'object') return '';
  return value[key] ?? '';
}

function buildSeoValue(metaTitle?: string, metaDescription?: string) {
  const normalizedTitle = metaTitle?.trim() || '';
  const normalizedDescription = metaDescription?.trim() || '';

  if (!normalizedTitle && !normalizedDescription) return null;

  return {
    metaTitle: normalizedTitle,
    metaDescription: normalizedDescription,
  };
}

function generateId(_prefix: string) {
  if (typeof crypto !== 'undefined' && 'randomUUID' in crypto) {
    return crypto.randomUUID();
  }
  return `00000000-0000-4000-8000-${`${Date.now()}`.padStart(12, '0').slice(-12)}`;
}

const statusOptions = [
  { value: 'draft', label: 'Draft' },
  { value: 'published', label: 'Published' },
  { value: 'archived', label: 'Archived' },
];

export const collectionConfigs: Record<CollectionName, CollectionConfig> = {
  pages: {
    collectionName: 'pages',
    title: 'Páginas',
    singularTitle: 'página',
    basePath: '/admin/pages',
    emptyMessage: 'No hay páginas registradas todavía.',
    getAll: () => pagesService.getAllPages(),
    getById: (id) => pagesService.getPageById(id),
    create: (payload) => pagesService.createPage(payload),
    update: (id, payload) => pagesService.updatePage(id, payload),
    remove: (id) => pagesService.deletePage(id),
    fields: [
      { name: 'slug', label: 'Slug / Page Key', type: 'text', required: true, description: 'Usa la clave estable de la página, por ejemplo: home, about, contact, careers.' },
      { name: 'title', label: 'SEO Title', type: 'text', multilingual: true, required: true },
      { name: 'description', label: 'SEO Description', type: 'textarea', multilingual: true, rows: 3 },
    ],
    toFormValues: (item) => ({
      slug: item?.page_key ?? item?.id ?? '',
      title_es: item?.title_es ?? '',
      title_en: item?.title_en ?? '',
      description_es: item?.description_es ?? '',
      description_en: item?.description_en ?? '',
    }),
    fromFormValues: (values) => ({
      slug: values.slug,
      title_es: values.title_es,
      title_en: values.title_en,
      description_es: values.description_es,
      description_en: values.description_en,
    }),
  },
  services: {
    collectionName: 'services',
    title: 'Servicios',
    singularTitle: 'servicio',
    basePath: '/admin/services',
    emptyMessage: 'No hay servicios cargados todavía.',
    getAll: () => servicesService.getServices(),
    getById: (id) => servicesService.getServiceById(id),
    create: (payload) => servicesService.createService(payload),
    update: (id, payload) => servicesService.updateService(id, payload),
    remove: (id) => servicesService.deleteService(id),
    fields: [
      { name: 'title', label: 'Title', type: 'text', multilingual: true, required: true },
      { name: 'slug', label: 'Slug', type: 'text', multilingual: true, required: true },
      { name: 'excerpt', label: 'Excerpt', type: 'textarea', multilingual: true, rows: 3 },
      { name: 'content', label: 'Content', type: 'textarea', multilingual: true, rows: 6 },
      { name: 'seo_meta_title', label: 'SEO Title', type: 'text', multilingual: true },
      { name: 'seo_meta_description', label: 'SEO Description', type: 'textarea', multilingual: true, rows: 3 },
      { name: 'hero_image', label: 'Hero Image Path', type: 'text' },
      { name: 'featured_image', label: 'Featured Image Path', type: 'text' },
      { name: 'technologies_csv', label: 'Technologies', type: 'textarea', rows: 2, description: 'Separadas por coma o salto de línea.' },
      { name: 'related_case_studies_csv', label: 'Related Case Study Slugs', type: 'textarea', rows: 2, description: 'Usa slugs ES/EN separados por coma.' },
      { name: 'capabilities_json', label: 'Capabilities JSON', type: 'textarea', rows: 8, description: 'Array JSON con title_es, title_en, description_es, description_en.' },
      { name: 'benefits_json', label: 'Benefits JSON', type: 'textarea', rows: 8, description: 'Array JSON con title_es, title_en, description_es, description_en.' },
      { name: 'status', label: 'Status', type: 'select', required: true, options: statusOptions },
      { name: 'order', label: 'Display Order', type: 'number', required: true },
      { name: 'featured', label: 'Featured', type: 'checkbox' },
    ],
    toFormValues: (item) => ({
      title_es: item?.title_es ?? '',
      title_en: item?.title_en ?? '',
      slug_es: item?.slug_es ?? '',
      slug_en: item?.slug_en ?? '',
      excerpt_es: item?.excerpt_es ?? '',
      excerpt_en: item?.excerpt_en ?? '',
      content_es: item?.content_es ?? '',
      content_en: item?.content_en ?? '',
      seo_meta_title_es: serializeSeoValue(item?.seo_es, 'metaTitle'),
      seo_meta_title_en: serializeSeoValue(item?.seo_en, 'metaTitle'),
      seo_meta_description_es: serializeSeoValue(item?.seo_es, 'metaDescription'),
      seo_meta_description_en: serializeSeoValue(item?.seo_en, 'metaDescription'),
      hero_image: item?.hero_image ?? '',
      featured_image: item?.featured_image ?? '',
      technologies_csv: serializeCsv(item?.technologies),
      related_case_studies_csv: serializeCsv(item?.related_case_studies),
      capabilities_json: serializeJson(item?.capabilities),
      benefits_json: serializeJson(item?.benefits),
      status: item?.status ?? 'published',
      order: item?.order ?? 0,
      featured: !!item?.featured,
    }),
    fromFormValues: (values, current) => ({
      ...(current ? {} : { id: generateId('service') }),
      language: 'en',
      status: values.status,
      title: values.title_en,
      slug: values.slug_en,
      excerpt: values.excerpt_en,
      content: values.content_en,
      title_es: values.title_es,
      title_en: values.title_en,
      slug_es: values.slug_es,
      slug_en: values.slug_en,
      excerpt_es: values.excerpt_es,
      excerpt_en: values.excerpt_en,
      content_es: values.content_es,
      content_en: values.content_en,
      seo_es: buildSeoValue(values.seo_meta_title_es, values.seo_meta_description_es),
      seo_en: buildSeoValue(values.seo_meta_title_en, values.seo_meta_description_en),
      hero_image: values.hero_image || null,
      featured_image: values.featured_image || values.hero_image || null,
      technologies: parseCsv(values.technologies_csv),
      related_case_studies: parseCsv(values.related_case_studies_csv),
      capabilities: parseJson(values.capabilities_json, []),
      benefits: parseJson(values.benefits_json, []),
      order: Number(values.order || 0),
      featured: !!values.featured,
      updated_at: new Date().toISOString(),
    }),
  },
  partners: {
    collectionName: 'partners',
    title: 'Partners',
    singularTitle: 'partner',
    basePath: '/admin/partners',
    emptyMessage: 'No hay partners cargados todavía.',
    getAll: () => partnersService.getAllPartners(),
    getById: (id) => partnersService.getPartnerById(id),
    create: (payload) => partnersService.createPartner(payload),
    update: (id, payload) => partnersService.updatePartner(id, payload),
    remove: (id) => partnersService.deletePartner(id),
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text', required: true },
      { name: 'logo_url', label: 'Logo Path', type: 'text' },
      { name: 'website_url', label: 'Website URL', type: 'text' },
      { name: 'description', label: 'Description', type: 'textarea', multilingual: true, rows: 3 },
      { name: 'status', label: 'Status', type: 'select', required: true, options: statusOptions },
      { name: 'order', label: 'Display Order', type: 'number', required: true },
      { name: 'featured', label: 'Featured', type: 'checkbox' },
    ],
    toFormValues: (item) => ({
      name: item?.name ?? '',
      slug: item?.slug ?? '',
      logo_url: item?.logo_url ?? '',
      website_url: item?.website_url ?? '',
      description_es: item?.description_es ?? '',
      description_en: item?.description_en ?? '',
      status: item?.status ?? 'published',
      order: item?.order ?? 0,
      featured: !!item?.featured,
    }),
    fromFormValues: (values, current) => ({
      ...(current ? {} : { id: generateId('partner') }),
      name: values.name,
      slug: values.slug,
      logo_url: normalizeMediaPath(values.logo_url),
      website_url: values.website_url || null,
      description_es: values.description_es,
      description_en: values.description_en,
      status: values.status,
      order: Number(values.order || 0),
      featured: !!values.featured,
      updated_at: new Date().toISOString(),
    }),
  },
  serviceCategories: {
    collectionName: 'serviceCategories',
    title: 'Service Categories',
    singularTitle: 'service category',
    basePath: '/admin/service-categories',
    emptyMessage: 'No hay categorías todavía.',
    getAll: () => serviceCategoriesService.getAllServiceCategories(),
    getById: (id) => serviceCategoriesService.getServiceCategoryById(id),
    create: (payload) => serviceCategoriesService.createServiceCategory(payload),
    update: (id, payload) => serviceCategoriesService.updateServiceCategory(id, payload),
    remove: (id) => serviceCategoriesService.deleteServiceCategory(id),
    fields: [
      { name: 'title', label: 'Title', type: 'text', multilingual: true, required: true },
      { name: 'slug', label: 'Slug', type: 'text', multilingual: true, required: true },
      { name: 'description', label: 'Description', type: 'textarea', multilingual: true, rows: 3 },
      { name: 'seo_meta_title', label: 'SEO Title', type: 'text', multilingual: true },
      { name: 'seo_meta_description', label: 'SEO Description', type: 'textarea', multilingual: true, rows: 3 },
      { name: 'category_slug', label: 'Category Key', type: 'text', required: true, description: 'Clave estable para agrupar servicios, por ejemplo: data-delivery.' },
      { name: 'icon', label: 'Icon', type: 'text' },
      { name: 'status', label: 'Status', type: 'select', required: true, options: statusOptions },
      { name: 'order', label: 'Display Order', type: 'number', required: true },
    ],
    toFormValues: (item) => ({
      title_es: item?.title_es ?? '',
      title_en: item?.title_en ?? '',
      slug_es: item?.slug_es ?? '',
      slug_en: item?.slug_en ?? '',
      description_es: item?.description_es ?? '',
      description_en: item?.description_en ?? '',
      seo_meta_title_es: serializeSeoValue(item?.seo_es, 'metaTitle'),
      seo_meta_title_en: serializeSeoValue(item?.seo_en, 'metaTitle'),
      seo_meta_description_es: serializeSeoValue(item?.seo_es, 'metaDescription'),
      seo_meta_description_en: serializeSeoValue(item?.seo_en, 'metaDescription'),
      category_slug: item?.category_slug ?? item?.categorySlug ?? '',
      icon: item?.icon ?? '',
      status: item?.status ?? 'published',
      order: item?.order ?? 0,
    }),
    fromFormValues: (values, current) => ({
      ...(current ? {} : { id: generateId('service-category') }),
      title_es: values.title_es,
      title_en: values.title_en,
      slug_es: values.slug_es,
      slug_en: values.slug_en,
      description_es: values.description_es || null,
      description_en: values.description_en || null,
      seo_es: buildSeoValue(values.seo_meta_title_es, values.seo_meta_description_es),
      seo_en: buildSeoValue(values.seo_meta_title_en, values.seo_meta_description_en),
      category_slug: values.category_slug,
      icon: values.icon || null,
      status: values.status,
      order: Number(values.order || 0),
      updated_at: new Date().toISOString(),
    }),
  },
  industries: {
    collectionName: 'industries',
    title: 'Industrias',
    singularTitle: 'industria',
    basePath: '/admin/industries',
    emptyMessage: 'No hay industrias cargadas todavía.',
    getAll: () => industriesService.getAllIndustries(),
    getById: (id) => industriesService.getIndustryById(id),
    create: (payload) => industriesService.createIndustry(payload),
    update: (id, payload) => industriesService.updateIndustry(id, payload),
    remove: (id) => industriesService.deleteIndustry(id),
    fields: [
      { name: 'title', label: 'Title', type: 'text', multilingual: true, required: true },
      { name: 'slug', label: 'Slug', type: 'text', multilingual: true, required: true },
      { name: 'excerpt', label: 'Excerpt', type: 'textarea', multilingual: true, rows: 3 },
      { name: 'content', label: 'Content', type: 'textarea', multilingual: true, rows: 6 },
      { name: 'seo_meta_title', label: 'SEO Title', type: 'text', multilingual: true },
      { name: 'seo_meta_description', label: 'SEO Description', type: 'textarea', multilingual: true, rows: 3 },
      { name: 'featured_image', label: 'Featured Image Path', type: 'text' },
      { name: 'discovery_description', label: 'Discovery Description', type: 'textarea', multilingual: true, rows: 3 },
      { name: 'challenges', label: 'Challenges', type: 'textarea', multilingual: true, rows: 4, description: 'Un ítem por línea.' },
      { name: 'value', label: 'How We Help', type: 'textarea', multilingual: true, rows: 4, description: 'Un ítem por línea.' },
      { name: 'solution_tags_csv', label: 'Solution / Technology Tags', type: 'textarea', rows: 3, description: 'Usa claves separadas por coma o salto de línea. Ej: data-strategy, business-intelligence.' },
      { name: 'related_case_study_ids_csv', label: 'Related Case Study IDs', type: 'textarea', rows: 2, description: 'IDs separados por coma o salto de línea.' },
      { name: 'status', label: 'Status', type: 'select', required: true, options: statusOptions },
      { name: 'order', label: 'Display Order', type: 'number', required: true },
    ],
    toFormValues: (item) => ({
      title_es: item?.title_es ?? '',
      title_en: item?.title_en ?? '',
      slug_es: item?.slug_es ?? '',
      slug_en: item?.slug_en ?? '',
      excerpt_es: item?.excerpt_es ?? item?.description_es ?? '',
      excerpt_en: item?.excerpt_en ?? item?.description_en ?? '',
      content_es: item?.content_es ?? '',
      content_en: item?.content_en ?? '',
      seo_meta_title_es: serializeSeoValue(item?.seo_es, 'metaTitle'),
      seo_meta_title_en: serializeSeoValue(item?.seo_en, 'metaTitle'),
      seo_meta_description_es: serializeSeoValue(item?.seo_es, 'metaDescription'),
      seo_meta_description_en: serializeSeoValue(item?.seo_en, 'metaDescription'),
      featured_image: item?.featured_image ?? '',
      discovery_description_es: item?.discovery_description_es ?? item?.description_es ?? '',
      discovery_description_en: item?.discovery_description_en ?? item?.description_en ?? '',
      challenges_es: serializeLines(item?.challenges_es),
      challenges_en: serializeLines(item?.challenges_en),
      value_es: serializeLines(item?.value_es),
      value_en: serializeLines(item?.value_en),
      solution_tags_csv: serializeCsv(item?.solution_tags),
      related_case_study_ids_csv: serializeCsv(item?.related_case_study_ids),
      status: item?.status ?? 'published',
      order: item?.order ?? 0,
    }),
    fromFormValues: (values, current) => ({
      ...(current ? {} : { id: generateId('industry') }),
      title_es: values.title_es,
      title_en: values.title_en,
      slug_es: values.slug_es,
      slug_en: values.slug_en,
      description_es: values.excerpt_es,
      description_en: values.excerpt_en,
      excerpt_es: values.excerpt_es,
      excerpt_en: values.excerpt_en,
      content_es: values.content_es,
      content_en: values.content_en,
      seo_es: buildSeoValue(values.seo_meta_title_es, values.seo_meta_description_es),
      seo_en: buildSeoValue(values.seo_meta_title_en, values.seo_meta_description_en),
      discovery_description_es: values.discovery_description_es || values.excerpt_es || null,
      discovery_description_en: values.discovery_description_en || values.excerpt_en || null,
      challenges_es: parseLines(values.challenges_es),
      challenges_en: parseLines(values.challenges_en),
      value_es: parseLines(values.value_es),
      value_en: parseLines(values.value_en),
      solution_tags: parseCsv(values.solution_tags_csv),
      related_case_study_ids: parseCsv(values.related_case_study_ids_csv),
      featured_image: values.featured_image || null,
      status: values.status,
      order: Number(values.order || 0),
      updated_at: new Date().toISOString(),
    }),
  },
  caseStudies: {
    collectionName: 'caseStudies',
    title: 'Casos de éxito',
    singularTitle: 'caso de éxito',
    basePath: '/admin/case-studies',
    emptyMessage: 'No hay casos de éxito cargados todavía.',
    getAll: () => caseStudiesService.getAllCaseStudies(),
    getById: (id) => caseStudiesService.getCaseStudyById(id),
    create: (payload) => caseStudiesService.createCaseStudy(payload),
    update: (id, payload) => caseStudiesService.updateCaseStudy(id, payload),
    remove: (id) => caseStudiesService.deleteCaseStudy(id),
    fields: [
      { name: 'client', label: 'Client', type: 'text', required: true },
      { name: 'title', label: 'Title', type: 'text', multilingual: true, required: true },
      { name: 'slug', label: 'Slug', type: 'text', multilingual: true, required: true },
      { name: 'excerpt', label: 'Excerpt', type: 'textarea', multilingual: true, rows: 3 },
      { name: 'seo_meta_title', label: 'SEO Title', type: 'text', multilingual: true },
      { name: 'seo_meta_description', label: 'SEO Description', type: 'textarea', multilingual: true, rows: 3 },
      { name: 'challenge', label: 'Challenge', type: 'textarea', multilingual: true, rows: 4 },
      { name: 'solution', label: 'Solution', type: 'textarea', multilingual: true, rows: 4 },
      { name: 'results', label: 'Results', type: 'textarea', multilingual: true, rows: 4, description: 'Métricas separadas por coma o salto de línea.' },
      { name: 'discovery_summary', label: 'Discovery Summary', type: 'textarea', multilingual: true, rows: 3 },
      { name: 'public_title', label: 'Public Title', type: 'text', multilingual: true, description: 'Título neutral o comercial para el sitio público.' },
      { name: 'public_client_name', label: 'Public Client Name', type: 'text', multilingual: true, description: 'Si no autorizan mostrar marca, usa una versión anonimizada. Ej: Empresa del sector retail en Latinoamérica.' },
      { name: 'show_client_identity', label: 'Show client identity publicly', type: 'checkbox' },
      { name: 'region', label: 'Region', type: 'text', multilingual: true, placeholder: 'Latinoamérica / Colombia / North America' },
      { name: 'solution_type', label: 'Solution Type', type: 'text', multilingual: true, placeholder: 'Gobierno de datos / IA aplicada / Analítica ejecutiva' },
      { name: 'objective', label: 'Objective', type: 'textarea', multilingual: true, rows: 3, description: 'Qué quería lograr el cliente en lenguaje claro.' },
      { name: 'business_pains', label: 'Business Pains', type: 'textarea', multilingual: true, rows: 4, description: 'Un dolor por línea. Ej: Información fragmentada, procesos manuales.' },
      { name: 'solution_description', label: 'Solution Description', type: 'textarea', multilingual: true, rows: 4, description: 'Explicación narrativa y pública de la solución.' },
      { name: 'capabilities_public', label: 'Public Capabilities', type: 'textarea', multilingual: true, rows: 4, description: 'Una capacidad por línea. Ej: Centralización de datos, automatización.' },
      { name: 'quantitative_impacts', label: 'Quantitative Impacts', type: 'textarea', multilingual: true, rows: 4, description: 'Un impacto cuantitativo por línea.' },
      { name: 'qualitative_impacts', label: 'Qualitative Impacts', type: 'textarea', multilingual: true, rows: 4, description: 'Un impacto cualitativo por línea.' },
      { name: 'metrics_text', label: 'Metrics Text', type: 'textarea', multilingual: true, rows: 3, description: 'Texto corto para explicar métricas cuando existan.' },
      { name: 'additional_opportunities', label: 'Additional Opportunities', type: 'textarea', multilingual: true, rows: 3, description: 'Cierre comercial opcional o siguiente oportunidad detectada.' },
      { name: 'cover_image', label: 'Cover Image Path', type: 'text' },
      { name: 'client_logo_url', label: 'Client Logo Path', type: 'text' },
      { name: 'gallery_images_csv', label: 'Gallery Images', type: 'textarea', rows: 4, description: 'Rutas separadas por coma o salto de línea. Máximo recomendado: 3 a 6.' },
      { name: 'technology_icons_csv', label: 'Technology Icons', type: 'textarea', rows: 3, description: 'Íconos o logos de tecnologías separados por coma o salto de línea.' },
      { name: 'testimonial', label: 'Testimonial', type: 'textarea', multilingual: true, rows: 3 },
      { name: 'show_testimonial', label: 'Show testimonial publicly', type: 'checkbox' },
      { name: 'case_type', label: 'Case Type', type: 'select', required: true, options: [
        { value: 'real', label: 'Real' },
        { value: 'placeholder', label: 'Placeholder / Prueba' },
      ] },
      { name: 'industry_id', label: 'Industry ID', type: 'text' },
      { name: 'related_industries_csv', label: 'Related Industry IDs', type: 'textarea', rows: 2, description: 'IDs separados por coma o salto de línea.' },
      { name: 'service_ids_csv', label: 'Service IDs', type: 'textarea', rows: 2, description: 'Separados por coma o salto de línea.' },
      { name: 'technology_tags_csv', label: 'Technology / Solution Tags', type: 'textarea', rows: 3, description: 'Usa claves separadas por coma o salto de línea. Ej: cloud, data-engineering.' },
      { name: 'related_case_study_ids_csv', label: 'Related Case Study IDs', type: 'textarea', rows: 2, description: 'IDs separados por coma o salto de línea.' },
      { name: 'published_date', label: 'Published Date', type: 'date' },
      { name: 'status', label: 'Status', type: 'select', required: true, options: statusOptions },
      { name: 'order', label: 'Display Order', type: 'number', required: true },
      { name: 'featured', label: 'Featured', type: 'checkbox' },
    ],
    toFormValues: (item) => ({
      client: item?.client ?? '',
      title_es: item?.title_es ?? '',
      title_en: item?.title_en ?? '',
      slug_es: item?.slug_es ?? '',
      slug_en: item?.slug_en ?? '',
      excerpt_es: item?.excerpt_es ?? '',
      excerpt_en: item?.excerpt_en ?? '',
      seo_meta_title_es: serializeSeoValue(item?.seo_es, 'metaTitle'),
      seo_meta_title_en: serializeSeoValue(item?.seo_en, 'metaTitle'),
      seo_meta_description_es: serializeSeoValue(item?.seo_es, 'metaDescription'),
      seo_meta_description_en: serializeSeoValue(item?.seo_en, 'metaDescription'),
      challenge_es: item?.challenge_es ?? '',
      challenge_en: item?.challenge_en ?? '',
      solution_es: item?.solution_es ?? '',
      solution_en: item?.solution_en ?? '',
      results_es: item?.results_es ?? '',
      results_en: item?.results_en ?? '',
      discovery_summary_es: item?.discovery_summary_es ?? item?.excerpt_es ?? '',
      discovery_summary_en: item?.discovery_summary_en ?? item?.excerpt_en ?? '',
      public_title_es: item?.public_title_es ?? '',
      public_title_en: item?.public_title_en ?? '',
      public_client_name_es: item?.public_client_name_es ?? '',
      public_client_name_en: item?.public_client_name_en ?? '',
      show_client_identity: !!item?.show_client_identity,
      region_es: item?.region_es ?? '',
      region_en: item?.region_en ?? '',
      solution_type_es: item?.solution_type_es ?? '',
      solution_type_en: item?.solution_type_en ?? '',
      objective_es: item?.objective_es ?? '',
      objective_en: item?.objective_en ?? '',
      business_pains_es: serializeLines(item?.business_pains_es),
      business_pains_en: serializeLines(item?.business_pains_en),
      solution_description_es: item?.solution_description_es ?? '',
      solution_description_en: item?.solution_description_en ?? '',
      capabilities_public_es: serializeLines(item?.capabilities_public_es),
      capabilities_public_en: serializeLines(item?.capabilities_public_en),
      quantitative_impacts_es: serializeLines(item?.quantitative_impacts_es),
      quantitative_impacts_en: serializeLines(item?.quantitative_impacts_en),
      qualitative_impacts_es: serializeLines(item?.qualitative_impacts_es),
      qualitative_impacts_en: serializeLines(item?.qualitative_impacts_en),
      metrics_text_es: item?.metrics_text_es ?? '',
      metrics_text_en: item?.metrics_text_en ?? '',
      additional_opportunities_es: item?.additional_opportunities_es ?? '',
      additional_opportunities_en: item?.additional_opportunities_en ?? '',
      cover_image: item?.cover_image ?? '',
      client_logo_url: item?.client_logo_url ?? '',
      gallery_images_csv: serializeCsv(item?.gallery_images),
      technology_icons_csv: serializeCsv(item?.technology_icons),
      testimonial_es: item?.testimonial_es ?? '',
      testimonial_en: item?.testimonial_en ?? '',
      show_testimonial: !!item?.show_testimonial,
      case_type: item?.case_type ?? 'real',
      industry_id: item?.industry_id ?? '',
      related_industries_csv: serializeCsv(item?.related_industries),
      service_ids_csv: serializeCsv(item?.service_ids),
      technology_tags_csv: serializeCsv(item?.technology_tags),
      related_case_study_ids_csv: serializeCsv(item?.related_case_study_ids),
      published_date: item?.published_date ?? '',
      status: item?.status ?? 'published',
      order: item?.order ?? 0,
      featured: !!item?.featured,
    }),
    fromFormValues: (values, current) => ({
      ...(current ? {} : { id: generateId('case-study') }),
      language: 'en',
      status: values.status,
      title: values.title_en,
      slug: values.slug_en,
      excerpt: values.excerpt_en,
      content: values.solution_en,
      client: values.client,
      title_es: values.title_es,
      title_en: values.title_en,
      slug_es: values.slug_es,
      slug_en: values.slug_en,
      excerpt_es: values.excerpt_es,
      excerpt_en: values.excerpt_en,
      seo_es: buildSeoValue(values.seo_meta_title_es, values.seo_meta_description_es),
      seo_en: buildSeoValue(values.seo_meta_title_en, values.seo_meta_description_en),
      content_es: values.solution_es,
      content_en: values.solution_en,
      challenge_es: values.challenge_es,
      challenge_en: values.challenge_en,
      solution_es: values.solution_es,
      solution_en: values.solution_en,
      results_es: values.results_es,
      results_en: values.results_en,
      discovery_summary_es: values.discovery_summary_es || values.excerpt_es || null,
      discovery_summary_en: values.discovery_summary_en || values.excerpt_en || null,
      public_title_es: values.public_title_es || null,
      public_title_en: values.public_title_en || null,
      public_client_name_es: values.public_client_name_es || null,
      public_client_name_en: values.public_client_name_en || null,
      show_client_identity: !!values.show_client_identity,
      region_es: values.region_es || null,
      region_en: values.region_en || null,
      solution_type_es: values.solution_type_es || null,
      solution_type_en: values.solution_type_en || null,
      objective_es: values.objective_es || null,
      objective_en: values.objective_en || null,
      business_pains_es: parseLines(values.business_pains_es),
      business_pains_en: parseLines(values.business_pains_en),
      solution_description_es: values.solution_description_es || null,
      solution_description_en: values.solution_description_en || null,
      capabilities_public_es: parseLines(values.capabilities_public_es),
      capabilities_public_en: parseLines(values.capabilities_public_en),
      quantitative_impacts_es: parseLines(values.quantitative_impacts_es),
      quantitative_impacts_en: parseLines(values.quantitative_impacts_en),
      qualitative_impacts_es: parseLines(values.qualitative_impacts_es),
      qualitative_impacts_en: parseLines(values.qualitative_impacts_en),
      metrics_text_es: values.metrics_text_es || null,
      metrics_text_en: values.metrics_text_en || null,
      additional_opportunities_es: values.additional_opportunities_es || null,
      additional_opportunities_en: values.additional_opportunities_en || null,
      cover_image: values.cover_image || null,
      client_logo_url: values.client_logo_url || null,
      gallery_images: parseCsv(values.gallery_images_csv).map(normalizeMediaPath),
      technology_icons: parseCsv(values.technology_icons_csv).map(normalizeMediaPath),
      testimonial_es: values.testimonial_es || null,
      testimonial_en: values.testimonial_en || null,
      show_testimonial: !!values.show_testimonial,
      case_type: values.case_type || 'real',
      industry_id: values.industry_id || null,
      related_industries: parseCsv(values.related_industries_csv),
      service_ids: parseCsv(values.service_ids_csv),
      technology_tags: parseCsv(values.technology_tags_csv),
      related_case_study_ids: parseCsv(values.related_case_study_ids_csv),
      published_date: values.published_date || null,
      order: Number(values.order || 0),
      featured: !!values.featured,
      updated_at: new Date().toISOString(),
    }),
  },
  blogPosts: {
    collectionName: 'blogPosts',
    title: 'Insights',
    singularTitle: 'insight',
    basePath: '/admin/insights',
    emptyMessage: 'No hay insights cargados todavía.',
    getAll: () => blogPostsService.getAllBlogPosts(),
    getById: (id) => blogPostsService.getBlogPostById(id),
    create: (payload) => blogPostsService.createBlogPost(payload),
    update: (id, payload) => blogPostsService.updateBlogPost(id, payload),
    remove: (id) => blogPostsService.deleteBlogPost(id),
    fields: [
      { name: 'title', label: 'Title', type: 'text', multilingual: true, required: true },
      { name: 'slug', label: 'Slug', type: 'text', multilingual: true, required: true },
      { name: 'excerpt', label: 'Excerpt', type: 'textarea', multilingual: true, rows: 3 },
      { name: 'content', label: 'Content', type: 'textarea', multilingual: true, rows: 6 },
      { name: 'seo_meta_title', label: 'SEO Title', type: 'text', multilingual: true },
      { name: 'seo_meta_description', label: 'SEO Description', type: 'textarea', multilingual: true, rows: 3 },
      { name: 'author', label: 'Author', type: 'text' },
      { name: 'featured_image', label: 'Featured Image Path', type: 'text' },
      { name: 'category_ids_csv', label: 'Category IDs', type: 'textarea', rows: 2, description: 'Separados por coma o salto de línea.' },
      { name: 'tags_csv', label: 'Tags', type: 'textarea', rows: 2, description: 'Separados por coma o salto de línea.' },
      { name: 'display_variant', label: 'Display Variant', type: 'select', options: [
        { value: '', label: 'Default' },
        { value: 'default', label: 'Default' },
        { value: 'large', label: 'Large' },
        { value: 'compact', label: 'Compact' },
      ] },
      { name: 'content_blocks_json', label: 'Content Blocks JSON', type: 'textarea', rows: 8 },
      { name: 'published_date', label: 'Published Date', type: 'date' },
      { name: 'read_time', label: 'Read Time (minutes)', type: 'number' },
      { name: 'status', label: 'Status', type: 'select', required: true, options: statusOptions },
      { name: 'featured', label: 'Featured', type: 'checkbox' },
    ],
    toFormValues: (item) => ({
      title_es: item?.title_es ?? '',
      title_en: item?.title_en ?? '',
      slug_es: item?.slug_es ?? '',
      slug_en: item?.slug_en ?? '',
      excerpt_es: item?.excerpt_es ?? '',
      excerpt_en: item?.excerpt_en ?? '',
      content_es: item?.content_es ?? '',
      content_en: item?.content_en ?? '',
      seo_meta_title_es: serializeSeoValue(item?.seo_es, 'metaTitle'),
      seo_meta_title_en: serializeSeoValue(item?.seo_en, 'metaTitle'),
      seo_meta_description_es: serializeSeoValue(item?.seo_es, 'metaDescription'),
      seo_meta_description_en: serializeSeoValue(item?.seo_en, 'metaDescription'),
      author: item?.author ?? '',
      featured_image: item?.featured_image ?? '',
      category_ids_csv: serializeCsv(item?.category_ids),
      tags_csv: serializeCsv(item?.tags),
      display_variant: item?.display_variant ?? '',
      content_blocks_json: serializeJson(item?.content_blocks),
      published_date: item?.published_date ?? '',
      read_time: item?.read_time ?? '',
      status: item?.status ?? 'published',
      featured: !!item?.featured,
    }),
    fromFormValues: (values, current) => ({
      ...(current ? {} : { id: generateId('blog-post') }),
      language: 'en',
      status: values.status,
      title: values.title_en,
      slug: values.slug_en,
      excerpt: values.excerpt_en,
      content: values.content_en,
      title_es: values.title_es,
      title_en: values.title_en,
      slug_es: values.slug_es,
      slug_en: values.slug_en,
      excerpt_es: values.excerpt_es,
      excerpt_en: values.excerpt_en,
      content_es: values.content_es,
      content_en: values.content_en,
      seo_es: buildSeoValue(values.seo_meta_title_es, values.seo_meta_description_es),
      seo_en: buildSeoValue(values.seo_meta_title_en, values.seo_meta_description_en),
      author: values.author || null,
      featured_image: values.featured_image || null,
      category_ids: parseCsv(values.category_ids_csv),
      tags: parseCsv(values.tags_csv),
      display_variant: values.display_variant || null,
      content_blocks: parseJson(values.content_blocks_json, null),
      published_date: values.published_date || null,
      read_time: values.read_time ? Number(values.read_time) : null,
      featured: !!values.featured,
      updated_at: new Date().toISOString(),
    }),
  },
  blogCategories: {
    collectionName: 'blogCategories',
    title: 'Blog Categories',
    singularTitle: 'blog category',
    basePath: '/admin/blog-categories',
    emptyMessage: 'No hay categorías todavía.',
    getAll: () => blogCategoriesService.getAllBlogCategories(),
    getById: (id) => blogCategoriesService.getBlogCategoryById(id),
    create: (payload) => blogCategoriesService.createBlogCategory(payload),
    update: (id, payload) => blogCategoriesService.updateBlogCategory(id, payload),
    remove: (id) => blogCategoriesService.deleteBlogCategory(id),
    fields: [
      { name: 'title', label: 'Title', type: 'text', multilingual: true, required: true },
      { name: 'slug', label: 'Slug', type: 'text', multilingual: true, required: true },
      { name: 'description', label: 'Description', type: 'textarea', multilingual: true, rows: 3 },
      { name: 'status', label: 'Status', type: 'select', required: true, options: statusOptions },
      { name: 'order', label: 'Display Order', type: 'number', required: true },
    ],
    toFormValues: (item) => ({
      title_es: item?.title_es ?? '',
      title_en: item?.title_en ?? '',
      slug_es: item?.slug_es ?? '',
      slug_en: item?.slug_en ?? '',
      description_es: item?.description_es ?? '',
      description_en: item?.description_en ?? '',
      status: item?.status ?? 'published',
      order: item?.order ?? 0,
    }),
    fromFormValues: (values, current) => ({
      ...(current ? {} : { id: generateId('blog-category') }),
      title_es: values.title_es,
      title_en: values.title_en,
      slug_es: values.slug_es,
      slug_en: values.slug_en,
      description_es: values.description_es || null,
      description_en: values.description_en || null,
      status: values.status,
      order: Number(values.order || 0),
      updated_at: new Date().toISOString(),
    }),
  },
  insightEvents: {
    collectionName: 'insightEvents',
    title: 'Eventos de Insights',
    singularTitle: 'evento de insights',
    basePath: '/admin/insight-events',
    emptyMessage: 'No hay eventos de Insights cargados todavía.',
    getAll: () => insightEventsService.getAllInsightEvents(),
    getById: (id) => insightEventsService.getInsightEventById(id),
    create: (payload) => insightEventsService.createInsightEvent(payload),
    update: (id, payload) => insightEventsService.updateInsightEvent(id, payload),
    remove: (id) => insightEventsService.deleteInsightEvent(id),
    fields: [
      { name: 'title', label: 'Title', type: 'text', multilingual: true, required: true },
      { name: 'slug', label: 'Slug', type: 'text', multilingual: true, required: true },
      { name: 'label', label: 'Badge label', type: 'text', multilingual: true, required: true },
      { name: 'meta', label: 'Meta / category', type: 'text', multilingual: true, required: true },
      { name: 'description', label: 'Description', type: 'textarea', multilingual: true, rows: 4 },
      { name: 'format', label: 'Format', type: 'text', multilingual: true },
      { name: 'location', label: 'Location', type: 'text', multilingual: true },
      { name: 'audience', label: 'Audience', type: 'textarea', multilingual: true, rows: 4, description: 'Un perfil por línea.' },
      { name: 'takeaways', label: 'Takeaways', type: 'textarea', multilingual: true, rows: 4, description: 'Un takeaway por línea.' },
      { name: 'agenda_json', label: 'Agenda JSON', type: 'textarea', multilingual: true, rows: 8, description: 'Array JSON con time, title y description.' },
      { name: 'speakers_json', label: 'Speakers JSON', type: 'textarea', multilingual: true, rows: 6, description: 'Array JSON con name y role.' },
      { name: 'seats_note', label: 'Attendance note', type: 'textarea', multilingual: true, rows: 3 },
      { name: 'registration_title', label: 'Registration title', type: 'text', multilingual: true },
      { name: 'registration_description', label: 'Registration description', type: 'textarea', multilingual: true, rows: 3 },
      { name: 'iso_date', label: 'ISO date and time', type: 'text', required: true, placeholder: '2026-04-18T08:00:00-05:00' },
      { name: 'sponsor_logos_csv', label: 'Sponsor / partner logos', type: 'textarea', rows: 3, description: 'Dos rutas por línea o separadas por coma.' },
      { name: 'status', label: 'Status', type: 'select', required: true, options: statusOptions },
      { name: 'order', label: 'Display Order', type: 'number', required: true },
    ],
    toFormValues: (item) => ({
      title_es: item?.title_es ?? '',
      title_en: item?.title_en ?? '',
      slug_es: item?.slug_es ?? '',
      slug_en: item?.slug_en ?? '',
      label_es: item?.label_es ?? '',
      label_en: item?.label_en ?? '',
      meta_es: item?.meta_es ?? '',
      meta_en: item?.meta_en ?? '',
      description_es: item?.description_es ?? '',
      description_en: item?.description_en ?? '',
      format_es: item?.format_es ?? '',
      format_en: item?.format_en ?? '',
      location_es: item?.location_es ?? '',
      location_en: item?.location_en ?? '',
      audience_es: serializeLines(item?.audience_es),
      audience_en: serializeLines(item?.audience_en),
      takeaways_es: serializeLines(item?.takeaways_es),
      takeaways_en: serializeLines(item?.takeaways_en),
      agenda_json_es: serializeJson(item?.agenda_es),
      agenda_json_en: serializeJson(item?.agenda_en),
      speakers_json_es: serializeJson(item?.speakers_es),
      speakers_json_en: serializeJson(item?.speakers_en),
      seats_note_es: item?.seats_note_es ?? '',
      seats_note_en: item?.seats_note_en ?? '',
      registration_title_es: item?.registration_title_es ?? '',
      registration_title_en: item?.registration_title_en ?? '',
      registration_description_es: item?.registration_description_es ?? '',
      registration_description_en: item?.registration_description_en ?? '',
      iso_date: item?.iso_date ?? '',
      sponsor_logos_csv: serializeCsv(item?.sponsor_logos),
      status: item?.status ?? 'published',
      order: item?.order ?? 0,
    }),
    fromFormValues: (values, current) => ({
      ...(current ? {} : { id: generateId('insight-event') }),
      slug_es: values.slug_es,
      slug_en: values.slug_en,
      title_es: values.title_es,
      title_en: values.title_en,
      label_es: values.label_es,
      label_en: values.label_en,
      meta_es: values.meta_es,
      meta_en: values.meta_en,
      description_es: values.description_es || '',
      description_en: values.description_en || '',
      format_es: values.format_es || '',
      format_en: values.format_en || '',
      location_es: values.location_es || '',
      location_en: values.location_en || '',
      audience_es: parseLines(values.audience_es),
      audience_en: parseLines(values.audience_en),
      takeaways_es: parseLines(values.takeaways_es),
      takeaways_en: parseLines(values.takeaways_en),
      agenda_es: parseJson(values.agenda_json_es, []),
      agenda_en: parseJson(values.agenda_json_en, []),
      speakers_es: parseJson(values.speakers_json_es, []),
      speakers_en: parseJson(values.speakers_json_en, []),
      seats_note_es: values.seats_note_es || '',
      seats_note_en: values.seats_note_en || '',
      registration_title_es: values.registration_title_es || '',
      registration_title_en: values.registration_title_en || '',
      registration_description_es: values.registration_description_es || '',
      registration_description_en: values.registration_description_en || '',
      iso_date: values.iso_date || '',
      sponsor_logos: parseCsv(values.sponsor_logos_csv).map(normalizeMediaPath).filter(Boolean),
      status: values.status,
      order: Number(values.order || 0),
      updated_at: new Date().toISOString(),
    }),
  },
  insightLabs: {
    collectionName: 'insightLabs',
    title: 'Radar de Insights',
    singularTitle: 'item del radar',
    basePath: '/admin/insight-labs',
    emptyMessage: 'No hay items cargados para la franja de desarrollo.',
    getAll: () => insightLabsService.getAllInsightLabs(),
    getById: (id) => insightLabsService.getInsightLabById(id),
    create: (payload) => insightLabsService.createInsightLab(payload),
    update: (id, payload) => insightLabsService.updateInsightLab(id, payload),
    remove: (id) => insightLabsService.deleteInsightLab(id),
    fields: [
      { name: 'slug', label: 'Slug', type: 'text', multilingual: true, required: true },
      { name: 'label', label: 'Badge label', type: 'text', multilingual: true, required: true },
      { name: 'title', label: 'Title', type: 'text', multilingual: true, required: true },
      { name: 'meta', label: 'Meta', type: 'text', multilingual: true },
      { name: 'description', label: 'Description', type: 'textarea', multilingual: true, rows: 4 },
      { name: 'seo_meta_title', label: 'SEO Title', type: 'text', multilingual: true },
      { name: 'seo_meta_description', label: 'SEO Description', type: 'textarea', multilingual: true, rows: 3 },
      { name: 'overview', label: 'Overview', type: 'textarea', multilingual: true, rows: 4 },
      { name: 'problem', label: 'Problem / opportunity', type: 'textarea', multilingual: true, rows: 4 },
      { name: 'audience', label: 'Audience', type: 'textarea', multilingual: true, rows: 4, description: 'Un perfil por línea.' },
      { name: 'includes', label: 'What it includes', type: 'textarea', multilingual: true, rows: 4, description: 'Un punto por línea.' },
      { name: 'signals', label: 'Current progress signals', type: 'textarea', multilingual: true, rows: 4, description: 'Un punto por línea.' },
      { name: 'featured_image', label: 'Featured Image Path', type: 'text' },
      { name: 'content_blocks_json', label: 'Content Blocks JSON', type: 'textarea', rows: 8, description: 'Opcional. Usa el mismo formato modular de los insights.' },
      { name: 'status', label: 'Status', type: 'select', required: true, options: statusOptions },
      { name: 'order', label: 'Display Order', type: 'number', required: true },
    ],
    toFormValues: (item) => ({
      slug_es: item?.slug_es ?? '',
      slug_en: item?.slug_en ?? '',
      label_es: item?.label_es ?? '',
      label_en: item?.label_en ?? '',
      title_es: item?.title_es ?? '',
      title_en: item?.title_en ?? '',
      meta_es: item?.meta_es ?? '',
      meta_en: item?.meta_en ?? '',
      description_es: item?.description_es ?? '',
      description_en: item?.description_en ?? '',
      seo_meta_title_es: serializeSeoValue(item?.seo_es, 'metaTitle'),
      seo_meta_title_en: serializeSeoValue(item?.seo_en, 'metaTitle'),
      seo_meta_description_es: serializeSeoValue(item?.seo_es, 'metaDescription'),
      seo_meta_description_en: serializeSeoValue(item?.seo_en, 'metaDescription'),
      overview_es: item?.overview_es ?? '',
      overview_en: item?.overview_en ?? '',
      problem_es: item?.problem_es ?? '',
      problem_en: item?.problem_en ?? '',
      audience_es: serializeLines(item?.audience_es),
      audience_en: serializeLines(item?.audience_en),
      includes_es: serializeLines(item?.includes_es),
      includes_en: serializeLines(item?.includes_en),
      signals_es: serializeLines(item?.signals_es),
      signals_en: serializeLines(item?.signals_en),
      featured_image: item?.featured_image ?? '',
      content_blocks_json: serializeJson(item?.content_blocks),
      status: item?.status ?? 'published',
      order: item?.order ?? 0,
    }),
    fromFormValues: (values, current) => ({
      ...(current ? {} : { id: generateId('insight-lab') }),
      slug_es: values.slug_es,
      slug_en: values.slug_en,
      label_es: values.label_es,
      label_en: values.label_en,
      title_es: values.title_es,
      title_en: values.title_en,
      meta_es: values.meta_es || '',
      meta_en: values.meta_en || '',
      description_es: values.description_es || '',
      description_en: values.description_en || '',
      seo_es: buildSeoValue(values.seo_meta_title_es, values.seo_meta_description_es),
      seo_en: buildSeoValue(values.seo_meta_title_en, values.seo_meta_description_en),
      overview_es: values.overview_es || '',
      overview_en: values.overview_en || '',
      problem_es: values.problem_es || '',
      problem_en: values.problem_en || '',
      audience_es: parseLines(values.audience_es),
      audience_en: parseLines(values.audience_en),
      includes_es: parseLines(values.includes_es),
      includes_en: parseLines(values.includes_en),
      signals_es: parseLines(values.signals_es),
      signals_en: parseLines(values.signals_en),
      featured_image: values.featured_image || null,
      content_blocks: parseJson(values.content_blocks_json, null),
      status: values.status,
      order: Number(values.order || 0),
      updated_at: new Date().toISOString(),
    }),
  },
  jobs: {
    collectionName: 'jobs',
    title: 'Jobs',
    singularTitle: 'job',
    basePath: '/admin/jobs',
    emptyMessage: 'No hay jobs todavía.',
    getAll: () => jobsService.getAllJobs(),
    getById: (id) => jobsService.getJobById(id),
    create: (payload) => jobsService.createJob(payload),
    update: (id, payload) => jobsService.updateJob(id, payload),
    remove: (id) => jobsService.deleteJob(id),
    fields: [
      { name: 'title', label: 'Title', type: 'text', multilingual: true, required: true },
      { name: 'slug', label: 'Slug', type: 'text', multilingual: true, required: true },
      { name: 'excerpt', label: 'Summary', type: 'textarea', multilingual: true, rows: 3 },
      { name: 'overview', label: 'Overview', type: 'textarea', multilingual: true, rows: 6 },
      { name: 'seo_meta_title', label: 'SEO Title', type: 'text', multilingual: true },
      { name: 'seo_meta_description', label: 'SEO Description', type: 'textarea', multilingual: true, rows: 3 },
      { name: 'department', label: 'Department', type: 'text', multilingual: true },
      { name: 'location', label: 'Location', type: 'text', multilingual: true },
      { name: 'type', label: 'Type', type: 'text', multilingual: true },
      { name: 'modality', label: 'Modality', type: 'select', options: [
        { value: 'remote', label: 'Remote' },
        { value: 'hybrid', label: 'Hybrid' },
        { value: 'onsite', label: 'On-site' },
      ] },
      { name: 'seniority', label: 'Seniority', type: 'select', options: [
        { value: 'junior', label: 'Junior' },
        { value: 'mid', label: 'Mid' },
        { value: 'senior', label: 'Senior' },
      ] },
      { name: 'description', label: 'Description', type: 'textarea', multilingual: true, rows: 4 },
      { name: 'responsibilities', label: 'Responsibilities', type: 'textarea', multilingual: true, rows: 4, description: 'Un ítem por línea.' },
      { name: 'requirements', label: 'Requirements', type: 'textarea', multilingual: true, rows: 4 },
      { name: 'nice_to_have', label: 'Nice to have', type: 'textarea', multilingual: true, rows: 4, description: 'Un ítem por línea.' },
      { name: 'benefits', label: 'Benefits', type: 'textarea', multilingual: true, rows: 4 },
      { name: 'tools_and_ways_of_working', label: 'Tools & ways of working', type: 'textarea', multilingual: true, rows: 4, description: 'Un ítem por línea.' },
      { name: 'what_we_offer', label: 'What we offer', type: 'textarea', multilingual: true, rows: 4, description: 'Un ítem por línea.' },
      { name: 'hiring_process', label: 'Hiring process', type: 'textarea', multilingual: true, rows: 4, description: 'Un ítem por línea.' },
      { name: 'equal_opportunity_note', label: 'Equal opportunity note', type: 'textarea', multilingual: true, rows: 3 },
      { name: 'apply_cta_label', label: 'Apply CTA label', type: 'text', multilingual: true },
      { name: 'salary_visible', label: 'Show salary', type: 'checkbox' },
      { name: 'salary_min', label: 'Salary min', type: 'number' },
      { name: 'salary_max', label: 'Salary max', type: 'number' },
      { name: 'currency', label: 'Currency', type: 'text' },
      { name: 'published_date', label: 'Published Date', type: 'date' },
      { name: 'status', label: 'Status', type: 'select', required: true, options: statusOptions },
      { name: 'featured', label: 'Featured', type: 'checkbox' },
      { name: 'active', label: 'Active', type: 'checkbox' },
      { name: 'order', label: 'Display Order', type: 'number', required: true },
    ],
    toFormValues: (item) => ({
      title_es: item?.title_es ?? item?.title ?? '',
      title_en: item?.title_en ?? item?.title ?? '',
      slug_es: item?.slug_es ?? item?.slug ?? '',
      slug_en: item?.slug_en ?? item?.slug ?? '',
      excerpt_es: item?.excerpt_es ?? item?.excerpt ?? '',
      excerpt_en: item?.excerpt_en ?? item?.excerpt ?? '',
      overview_es: item?.overview_es ?? item?.content ?? '',
      overview_en: item?.overview_en ?? item?.content ?? '',
      seo_meta_title_es: serializeSeoValue(item?.seo_es, 'metaTitle'),
      seo_meta_title_en: serializeSeoValue(item?.seo_en, 'metaTitle'),
      seo_meta_description_es: serializeSeoValue(item?.seo_es, 'metaDescription'),
      seo_meta_description_en: serializeSeoValue(item?.seo_en, 'metaDescription'),
      department_es: item?.department_es ?? '',
      department_en: item?.department_en ?? '',
      location_es: item?.location_es ?? item?.location ?? '',
      location_en: item?.location_en ?? item?.location ?? '',
      type_es: item?.type_es ?? item?.type ?? '',
      type_en: item?.type_en ?? item?.type ?? '',
      modality: item?.modality ?? 'remote',
      seniority: item?.seniority ?? 'mid',
      description_es: item?.description_es ?? '',
      description_en: item?.description_en ?? '',
      responsibilities_es: serializeLines(item?.responsibilities_es),
      responsibilities_en: serializeLines(item?.responsibilities_en),
      requirements_es: item?.requirements_es ?? '',
      requirements_en: item?.requirements_en ?? '',
      nice_to_have_es: serializeLines(item?.nice_to_have_es),
      nice_to_have_en: serializeLines(item?.nice_to_have_en),
      benefits_es: item?.benefits_es ?? '',
      benefits_en: item?.benefits_en ?? '',
      tools_and_ways_of_working_es: serializeLines(item?.tools_and_ways_of_working_es),
      tools_and_ways_of_working_en: serializeLines(item?.tools_and_ways_of_working_en),
      what_we_offer_es: serializeLines(item?.what_we_offer_es),
      what_we_offer_en: serializeLines(item?.what_we_offer_en),
      hiring_process_es: serializeLines(item?.hiring_process_es),
      hiring_process_en: serializeLines(item?.hiring_process_en),
      equal_opportunity_note_es: item?.equal_opportunity_note_es ?? '',
      equal_opportunity_note_en: item?.equal_opportunity_note_en ?? '',
      apply_cta_label_es: item?.apply_cta_label_es ?? '',
      apply_cta_label_en: item?.apply_cta_label_en ?? '',
      salary_visible: !!item?.salary_visible,
      salary_min: item?.salary_min ?? '',
      salary_max: item?.salary_max ?? '',
      currency: item?.currency ?? 'USD',
      published_date: item?.published_date ?? '',
      status: item?.status ?? 'published',
      featured: !!item?.featured,
      active: item?.active ?? true,
      order: item?.order ?? 0,
    }),
    fromFormValues: (values, current) => ({
      ...(current ? {} : { id: generateId('job') }),
      language: 'en',
      status: values.status,
      title: values.title_en,
      slug: values.slug_en,
      title_es: values.title_es,
      title_en: values.title_en,
      slug_es: values.slug_es,
      slug_en: values.slug_en,
      excerpt: values.excerpt_en || null,
      excerpt_es: values.excerpt_es || null,
      excerpt_en: values.excerpt_en || null,
      seo_es: buildSeoValue(values.seo_meta_title_es, values.seo_meta_description_es),
      seo_en: buildSeoValue(values.seo_meta_title_en, values.seo_meta_description_en),
      content: values.overview_en || null,
      overview_es: values.overview_es || null,
      overview_en: values.overview_en || null,
      department_es: values.department_es || null,
      department_en: values.department_en || null,
      location: values.location_en || values.location_es || null,
      location_es: values.location_es || null,
      location_en: values.location_en || null,
      type: values.type_en || values.type_es || null,
      type_es: values.type_es || null,
      type_en: values.type_en || null,
      modality: values.modality || null,
      seniority: values.seniority || null,
      description_es: values.description_es || null,
      description_en: values.description_en || null,
      responsibilities_es: parseLines(values.responsibilities_es),
      responsibilities_en: parseLines(values.responsibilities_en),
      requirements_es: values.requirements_es || null,
      requirements_en: values.requirements_en || null,
      nice_to_have_es: parseLines(values.nice_to_have_es),
      nice_to_have_en: parseLines(values.nice_to_have_en),
      benefits_es: values.benefits_es || null,
      benefits_en: values.benefits_en || null,
      tools_and_ways_of_working_es: parseLines(values.tools_and_ways_of_working_es),
      tools_and_ways_of_working_en: parseLines(values.tools_and_ways_of_working_en),
      what_we_offer_es: parseLines(values.what_we_offer_es),
      what_we_offer_en: parseLines(values.what_we_offer_en),
      hiring_process_es: parseLines(values.hiring_process_es),
      hiring_process_en: parseLines(values.hiring_process_en),
      equal_opportunity_note_es: values.equal_opportunity_note_es || null,
      equal_opportunity_note_en: values.equal_opportunity_note_en || null,
      apply_cta_label_es: values.apply_cta_label_es || null,
      apply_cta_label_en: values.apply_cta_label_en || null,
      salary_visible: !!values.salary_visible,
      salary_min: values.salary_min ? Number(values.salary_min) : null,
      salary_max: values.salary_max ? Number(values.salary_max) : null,
      currency: values.currency || null,
      published_date: values.published_date || null,
      featured: !!values.featured,
      active: !!values.active,
      order: Number(values.order || 0),
      updated_at: new Date().toISOString(),
    }),
  },
  teamMembers: {
    collectionName: 'teamMembers',
    title: 'Miembros del equipo',
    singularTitle: 'miembro del equipo',
    basePath: '/admin/team-members',
    emptyMessage: 'No hay miembros del equipo cargados todavía.',
    getAll: () => teamMembersService.getAllTeamMembers(),
    getById: (id) => teamMembersService.getTeamMemberById(id),
    create: (payload) => teamMembersService.createTeamMember(payload),
    update: (id, payload) => teamMembersService.updateTeamMember(id, payload),
    remove: (id) => teamMembersService.deleteTeamMember(id),
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'position', label: 'Position', type: 'text', multilingual: true, required: true },
      { name: 'bio', label: 'Bio', type: 'textarea', multilingual: true, rows: 4 },
      { name: 'photo_url', label: 'Photo Path', type: 'text' },
      { name: 'linkedin_url', label: 'LinkedIn URL', type: 'text' },
      { name: 'email', label: 'Email', type: 'text' },
      { name: 'status', label: 'Status', type: 'select', required: true, options: statusOptions },
      { name: 'featured', label: 'Featured', type: 'checkbox' },
      { name: 'order', label: 'Display Order', type: 'number', required: true },
    ],
    toFormValues: (item) => ({
      name: item?.name ?? '',
      position_es: item?.position_es ?? '',
      position_en: item?.position_en ?? '',
      bio_es: item?.bio_es ?? '',
      bio_en: item?.bio_en ?? '',
      photo_url: item?.photo_url ?? '',
      linkedin_url: item?.linkedin_url ?? '',
      email: item?.email ?? '',
      status: item?.status ?? 'published',
      featured: !!item?.featured,
      order: item?.order ?? 0,
    }),
    fromFormValues: (values, current) => ({
      ...(current ? {} : { id: generateId('team-member') }),
      name: values.name,
      position_es: values.position_es,
      position_en: values.position_en,
      bio_es: values.bio_es,
      bio_en: values.bio_en,
      photo_url: values.photo_url || null,
      linkedin_url: values.linkedin_url || null,
      email: values.email || null,
      status: values.status,
      featured: !!values.featured,
      order: Number(values.order || 0),
      updated_at: new Date().toISOString(),
    }),
  },
  resources: {
    collectionName: 'resources',
    title: 'Resources',
    singularTitle: 'resource',
    basePath: '/admin/resources',
    emptyMessage: 'No hay resources todavía.',
    getAll: () => resourcesService.getAllResources(),
    getById: (id) => resourcesService.getResourceById(id),
    create: (payload) => resourcesService.createResource(payload),
    update: (id, payload) => resourcesService.updateResource(id, payload),
    remove: (id) => resourcesService.deleteResource(id),
    fields: [
      { name: 'title', label: 'Title', type: 'text', multilingual: true, required: true },
      { name: 'slug', label: 'Slug', type: 'text', multilingual: true, required: true },
      { name: 'type', label: 'Type', type: 'text', multilingual: true },
      { name: 'description', label: 'Description', type: 'textarea', multilingual: true, rows: 3 },
      { name: 'content', label: 'Content', type: 'textarea', multilingual: true, rows: 6 },
      { name: 'seo_meta_title', label: 'SEO Title', type: 'text', multilingual: true },
      { name: 'seo_meta_description', label: 'SEO Description', type: 'textarea', multilingual: true, rows: 3 },
      { name: 'featured_image', label: 'Featured Image Path', type: 'text' },
      { name: 'download_url', label: 'Download URL', type: 'text' },
      { name: 'file_url', label: 'File URL', type: 'text' },
      { name: 'file_type', label: 'File Type', type: 'text' },
      { name: 'published_date', label: 'Published Date', type: 'date' },
      { name: 'status', label: 'Status', type: 'select', required: true, options: statusOptions },
      { name: 'featured', label: 'Featured', type: 'checkbox' },
      { name: 'order', label: 'Display Order', type: 'number', required: true },
    ],
    toFormValues: (item) => ({
      title_es: item?.title_es ?? '',
      title_en: item?.title_en ?? '',
      slug_es: item?.slug_es ?? '',
      slug_en: item?.slug_en ?? '',
      type_es: item?.type_es ?? '',
      type_en: item?.type_en ?? '',
      description_es: item?.description_es ?? '',
      description_en: item?.description_en ?? '',
      content_es: item?.content_es ?? '',
      content_en: item?.content_en ?? '',
      seo_meta_title_es: serializeSeoValue(item?.seo_es, 'metaTitle'),
      seo_meta_title_en: serializeSeoValue(item?.seo_en, 'metaTitle'),
      seo_meta_description_es: serializeSeoValue(item?.seo_es, 'metaDescription'),
      seo_meta_description_en: serializeSeoValue(item?.seo_en, 'metaDescription'),
      featured_image: item?.featured_image ?? '',
      download_url: item?.download_url ?? item?.downloadUrl ?? '',
      file_url: item?.file_url ?? '',
      file_type: item?.file_type ?? '',
      published_date: item?.published_date ?? '',
      status: item?.status ?? 'published',
      featured: !!item?.featured,
      order: item?.order ?? 0,
    }),
    fromFormValues: (values, current) => ({
      ...(current ? {} : { id: generateId('resource') }),
      title_es: values.title_es,
      title_en: values.title_en,
      slug_es: values.slug_es,
      slug_en: values.slug_en,
      type_es: values.type_es || null,
      type_en: values.type_en || null,
      description_es: values.description_es || null,
      description_en: values.description_en || null,
      content_es: values.content_es || null,
      content_en: values.content_en || null,
      seo_es: buildSeoValue(values.seo_meta_title_es, values.seo_meta_description_es),
      seo_en: buildSeoValue(values.seo_meta_title_en, values.seo_meta_description_en),
      featured_image: values.featured_image || null,
      download_url: values.download_url || null,
      file_url: values.file_url || null,
      file_type: values.file_type || null,
      published_date: values.published_date || null,
      status: values.status,
      featured: !!values.featured,
      order: Number(values.order || 0),
      updated_at: new Date().toISOString(),
    }),
  },
  testimonials: {
    collectionName: 'testimonials',
    title: 'Testimonials',
    singularTitle: 'testimonial',
    basePath: '/admin/testimonials',
    emptyMessage: 'No hay testimonials todavía.',
    getAll: () => testimonialsService.getAllTestimonials(),
    getById: (id) => testimonialsService.getTestimonialById(id),
    create: (payload) => testimonialsService.createTestimonial(payload),
    update: (id, payload) => testimonialsService.updateTestimonial(id, payload),
    remove: (id) => testimonialsService.deleteTestimonial(id),
    fields: [
      { name: 'client_name', label: 'Client Name', type: 'text', required: true },
      { name: 'client_position', label: 'Client Position', type: 'text', multilingual: true },
      { name: 'client_company', label: 'Client Company', type: 'text' },
      { name: 'quote', label: 'Quote', type: 'textarea', multilingual: true, rows: 4, required: true },
      { name: 'photo_url', label: 'Photo Path', type: 'text' },
      { name: 'rating', label: 'Rating', type: 'number' },
      { name: 'status', label: 'Status', type: 'select', required: true, options: statusOptions },
      { name: 'order', label: 'Display Order', type: 'number', required: true },
    ],
    toFormValues: (item) => ({
      client_name: item?.client_name ?? item?.clientName ?? item?.name ?? '',
      client_position_es: item?.client_position_es ?? item?.clientPosition_es ?? '',
      client_position_en: item?.client_position_en ?? item?.clientPosition_en ?? '',
      client_company: item?.client_company ?? item?.clientCompany ?? item?.company ?? '',
      quote_es: item?.quote_es ?? item?.quote_es ?? item?.content_es ?? '',
      quote_en: item?.quote_en ?? item?.quote_en ?? item?.content_en ?? '',
      photo_url: item?.photo_url ?? item?.photo ?? '',
      rating: item?.rating ?? '',
      status: item?.status ?? 'published',
      order: item?.order ?? 0,
    }),
    fromFormValues: (values, current) => ({
      ...(current ? {} : { id: generateId('testimonial') }),
      name: values.client_name,
      client_name: values.client_name,
      client_position_es: values.client_position_es || null,
      client_position_en: values.client_position_en || null,
      client_company: values.client_company || null,
      company: values.client_company || null,
      quote_es: values.quote_es,
      quote_en: values.quote_en,
      content_es: values.quote_es,
      content_en: values.quote_en,
      photo_url: values.photo_url || null,
      rating: values.rating ? Number(values.rating) : null,
      status: values.status,
      order: Number(values.order || 0),
      updated_at: new Date().toISOString(),
    }),
  },
  homeSections: {
    collectionName: 'homeSections',
    title: 'Home Sections',
    singularTitle: 'home section',
    basePath: '/admin/home-sections',
    emptyMessage: 'No hay home sections todavía.',
    getAll: () => homeSectionsService.getAllHomeSections(),
    getById: (id) => homeSectionsService.getHomeSectionById(id),
    create: (payload) => homeSectionsService.createHomeSection(payload),
    update: (id, payload) => homeSectionsService.updateHomeSection(id, payload),
    remove: (id) => homeSectionsService.deleteHomeSection(id),
    fields: [
      { name: 'language', label: 'Language', type: 'select' as const, required: true, options: [
        { value: 'es', label: 'Spanish' },
        { value: 'en', label: 'English' }
      ]},
      { name: 'type', label: 'Section Type', type: 'select' as const, required: true, options: [
        { value: 'preHero', label: 'Pre Hero' },
        { value: 'hero', label: 'Hero' },
        { value: 'strategicBannerTriple', label: 'Strategic Banner Triple' },
        { value: 'logos', label: 'Logos / Authority' },
        { value: 'partners', label: 'Partners' },
        { value: 'clients', label: 'Clients' },
        { value: 'maturityJourney', label: 'Maturity Journey' },
        { value: 'serviceHighlights', label: 'Service Highlights' },
        { value: 'industryHighlights', label: 'Industry Highlights' },
        { value: 'caseHighlights', label: 'Case Highlights' },
        { value: 'insightsEditorial', label: 'Insights Editorial' },
        { value: 'testimonials', label: 'Testimonials' },
        { value: 'ctaBand', label: 'CTA Band' },
        { value: 'stats', label: 'Stats' },
        { value: 'custom', label: 'Custom' }
      ]},
      { name: 'title', label: 'Section Title / Headline', type: 'text' as const, description: 'Hero main phrase. En Home, el hero actual usa este campo como headline principal de la primera pantalla.' },
      { name: 'subtitle', label: 'Section Supporting Text', type: 'text' as const, description: 'Texto de soporte opcional. En Home acompaña el hero principal debajo del headline.' },
      { name: 'cta_label', label: 'Primary CTA Label', type: 'text' as const, description: 'Botón principal visible en la sección, si aplica.' },
      { name: 'cta_href', label: 'Primary CTA URL', type: 'text' as const, description: 'Ruta interna o URL del CTA principal.' },
      { name: 'order', label: 'Order', type: 'number' as const, required: true },
      { name: 'is_enabled', label: 'Enabled', type: 'checkbox' as const },
      { name: 'referenced_ids', label: 'Referenced IDs', type: 'text' as const, description: 'Comma-separated list of content IDs to reference' },
      { name: 'content', label: 'Content (JSON)', type: 'textarea' as const, rows: 10, description: 'Usa este bloque solo cuando la sección necesite contenido estructurado adicional.' },
      { name: 'config', label: 'Config (JSON)', type: 'textarea' as const, rows: 12, description: 'Hero: eyebrow, secondaryCtaLabel y secondaryCtaHref. Service Highlights: metricValue, metricLabel, featuredCardTitle, featuredCardText, featuredCardCtaLabel, featuredCardCtaHref. Insights Editorial: moreInsightsTitle, moreInsightsText, moreInsightsCtaLabel, moreInsightsCtaHref. Partners/Maturity: eyebrow, levels, partners. Strategic Banner Triple usa panels solo cuando aplique fuera del Home.' }
    ],
    toFormValues: (item) => ({
      language: item?.language ?? 'es',
      type: item?.type ?? 'hero',
      title: item?.title ?? '',
      subtitle: item?.subtitle ?? '',
      cta_label: item?.cta_label ?? '',
      cta_href: item?.cta_href ?? '',
      order: item?.order ?? 0,
      is_enabled: item?.is_enabled ?? true,
      referenced_ids: item?.referenced_ids?.join(', ') ?? '',
      content: item?.content ? JSON.stringify(item.content, null, 2) : '',
      config: item?.config ? JSON.stringify(item.config, null, 2) : ''
    }),
    fromFormValues: (values, current) => ({
      ...(current ? {} : { id: generateId('home-section') }),
      language: values.language,
      type: values.type,
      title: values.title || null,
      subtitle: values.subtitle || null,
      cta_label: values.cta_label || null,
      cta_href: values.cta_href || null,
      order: parseInt(values.order) || 0,
      is_enabled: !!values.is_enabled,
      referenced_ids: values.referenced_ids ? values.referenced_ids.split(',').map((id: string) => id.trim()).filter(Boolean) : [],
      content: values.content ? JSON.parse(values.content) : null,
      config: values.config ? JSON.parse(values.config) : null,
      updated_at: new Date().toISOString(),
    }),
  },
};

export function getCollectionConfig(collectionName: CollectionName) {
  return collectionConfigs[collectionName];
}
