export interface ClientLogoMarqueeItem {
  name: string;
  logo: string;
  scale?: number;
}

export const clientLogosMarquee = [
  '/assets/logos/clients-marquee/LOGO 4 72.svg',
  '/assets/logos/clients-marquee/LOGO ACHS.svg',
  '/assets/logos/clients-marquee/LOGO AES.svg',
  '/assets/logos/clients-marquee/LOGO AGROSUPER.svg',
  '/assets/logos/clients-marquee/LOGO Alcaldía Mayor de Bogotá.svg',
  '/assets/logos/clients-marquee/LOGO Alcaldía de Medellín.svg',
  '/assets/logos/clients-marquee/LOGO Arauco.svg',
  '/assets/logos/clients-marquee/LOGO Avianca.svg',
  '/assets/logos/clients-marquee/LOGO BCIE.svg',
  '/assets/logos/clients-marquee/LOGO Banco Agrario.svg',
  '/assets/logos/clients-marquee/LOGO Banco Aliado.svg',
  '/assets/logos/clients-marquee/LOGO Banco Central de Chile.svg',
  '/assets/logos/clients-marquee/LOGO Banco Estado.svg',
  '/assets/logos/clients-marquee/LOGO Banco de Chile.svg',
  '/assets/logos/clients-marquee/LOGO Bancolombia.svg',
  '/assets/logos/clients-marquee/LOGO Banistmo.svg',
  '/assets/logos/clients-marquee/LOGO Banmédica.svg',
  '/assets/logos/clients-marquee/LOGO Bci.svg',
  '/assets/logos/clients-marquee/LOGO Besalco.svg',
  '/assets/logos/clients-marquee/LOGO Bienestar Familiar.svg',
  '/assets/logos/clients-marquee/LOGO Bupa.svg',
  '/assets/logos/clients-marquee/LOGO CAC.svg',
  '/assets/logos/clients-marquee/LOGO Cafam.svg',
  '/assets/logos/clients-marquee/LOGO Carozzi.svg',
  '/assets/logos/clients-marquee/LOGO Celsia.svg',
  '/assets/logos/clients-marquee/LOGO Cencosud.svg',
  '/assets/logos/clients-marquee/LOGO Chilexpress.svg',
  '/assets/logos/clients-marquee/LOGO Claro.svg',
  '/assets/logos/clients-marquee/LOGO Clínica Las Condes.svg',
  '/assets/logos/clients-marquee/LOGO Clínica MEDS.svg',
  '/assets/logos/clients-marquee/LOGO Colsubsidio.svg',
  '/assets/logos/clients-marquee/LOGO Compensar.svg',
  '/assets/logos/clients-marquee/LOGO Coninsa.svg',
  '/assets/logos/clients-marquee/LOGO Constructora Bolívar.svg',
  '/assets/logos/clients-marquee/LOGO Contraloría General de la República.svg',
  '/assets/logos/clients-marquee/LOGO Corona.svg',
  '/assets/logos/clients-marquee/LOGO Crystal.svg',
  '/assets/logos/clients-marquee/LOGO Cámara de Comercio.svg',
  '/assets/logos/clients-marquee/LOGO Data+AI Summit.svg',
  '/assets/logos/clients-marquee/LOGO EAFIT.svg',
  '/assets/logos/clients-marquee/LOGO EPM.svg',
  '/assets/logos/clients-marquee/LOGO Echeverria Izquierdo.svg',
  '/assets/logos/clients-marquee/LOGO Efecty.svg',
  '/assets/logos/clients-marquee/LOGO Enel.svg',
  '/assets/logos/clients-marquee/LOGO Entel.svg',
  '/assets/logos/clients-marquee/LOGO Falabella.svg',
  '/assets/logos/clients-marquee/LOGO Farmacias Ahumada.svg',
  '/assets/logos/clients-marquee/LOGO Fenalco.svg',
  '/assets/logos/clients-marquee/LOGO Finaktiva.svg',
  '/assets/logos/clients-marquee/LOGO Flamingo.svg',
  '/assets/logos/clients-marquee/LOGO GTD.svg',
  '/assets/logos/clients-marquee/LOGO Grupo Argos.svg',
  '/assets/logos/clients-marquee/LOGO Grupo Bancolombia.svg',
  '/assets/logos/clients-marquee/LOGO Grupo Gloria.svg',
  '/assets/logos/clients-marquee/LOGO Grupo Phoenix.svg',
  '/assets/logos/clients-marquee/LOGO Grupo Rica_color.svg',
  '/assets/logos/clients-marquee/LOGO Grupo Security.svg',
  '/assets/logos/clients-marquee/LOGO Grupo Sura.svg',
  '/assets/logos/clients-marquee/LOGO Haceb.svg',
  '/assets/logos/clients-marquee/LOGO Isa Intervial.svg',
  '/assets/logos/clients-marquee/LOGO Latam Airlines.svg',
  '/assets/logos/clients-marquee/LOGO Metro de Medellín.svg',
  '/assets/logos/clients-marquee/LOGO Ministerio de Educación.svg',
  '/assets/logos/clients-marquee/LOGO Mutual de Seguridad.svg',
  '/assets/logos/clients-marquee/LOGO Nap del Caribe_color.svg',
  '/assets/logos/clients-marquee/LOGO Postobon.svg',
  '/assets/logos/clients-marquee/LOGO Principal.svg',
  '/assets/logos/clients-marquee/LOGO Protección.svg',
  '/assets/logos/clients-marquee/LOGO RENAULT SOFASA.svg',
  '/assets/logos/clients-marquee/LOGO Renault.svg',
  '/assets/logos/clients-marquee/LOGO Renting Colombia.svg',
  '/assets/logos/clients-marquee/LOGO Sapiencia.svg',
  '/assets/logos/clients-marquee/LOGO Seguros del Estado.svg',
  '/assets/logos/clients-marquee/LOGO Sena.svg',
  '/assets/logos/clients-marquee/LOGO Servientrega.svg',
  '/assets/logos/clients-marquee/LOGO Surtigas.svg',
  '/assets/logos/clients-marquee/LOGO TCC.svg',
  '/assets/logos/clients-marquee/LOGO Tuya.svg',
  '/assets/logos/clients-marquee/LOGO UDP.svg',
  '/assets/logos/clients-marquee/LOGO UNE.svg',
  '/assets/logos/clients-marquee/LOGO USFQ.svg',
  '/assets/logos/clients-marquee/LOGO Universidad Católica CHILE.svg',
  '/assets/logos/clients-marquee/LOGO Universidad Mayor CHILE.svg',
  '/assets/logos/clients-marquee/LOGO Vélez.svg',
  '/assets/logos/clients-marquee/LOGO Western Union.svg',
  '/assets/logos/clients-marquee/LOGO XM.svg',
  '/assets/logos/clients-marquee/LOGO assa.svg',
  '/assets/logos/clients-marquee/LOGO cmpc.svg',
  '/assets/logos/clients-marquee/LOGO concha y toro.svg',
  '/assets/logos/clients-marquee/LOGO esval.svg',
  '/assets/logos/clients-marquee/LOGO pei.svg',
  '/assets/logos/clients-marquee/LOGO vtr.svg',
  '/assets/logos/clients-marquee/LOGO Área Metropolitana.svg',
  '/assets/logos/clients-marquee/LOGO éxito.svg',
  '/assets/logos/clients-marquee/Logo Argos.svg',
  '/assets/logos/clients-marquee/Microsoft_logo_(2012).svg',
] as const;

const whitespaceHeavyLogoScale: Record<string, number> = {
  '/assets/logos/clients-marquee/LOGO Sapiencia.svg': 1.54,
  '/assets/logos/clients-marquee/LOGO USFQ.svg': 1.5,
  '/assets/logos/clients-marquee/LOGO Universidad Católica CHILE.svg': 1.44,
  '/assets/logos/clients-marquee/LOGO Universidad Mayor CHILE.svg': 1.36,
  '/assets/logos/clients-marquee/LOGO Área Metropolitana.svg': 1.14,
  '/assets/logos/clients-marquee/LOGO CAC.svg': 1.3,
  '/assets/logos/clients-marquee/LOGO RENAULT SOFASA.svg': 1.28,
  '/assets/logos/clients-marquee/LOGO esval.svg': 1.34,
  '/assets/logos/clients-marquee/LOGO Banco Agrario.svg': 1.1,
  '/assets/logos/clients-marquee/LOGO Alcaldía de Medellín.svg': 1.44,
  '/assets/logos/clients-marquee/LOGO Alcaldía Mayor de Bogotá.svg': 1.08,
  '/assets/logos/clients-marquee/LOGO Coninsa.svg': 1.08,
  '/assets/logos/clients-marquee/LOGO UNE.svg': 1.18,
  '/assets/logos/clients-marquee/LOGO Grupo Phoenix.svg': 1.34,
  '/assets/logos/clients-marquee/LOGO Isa Intervial.svg': 1.4,
  '/assets/logos/clients-marquee/LOGO Efecty.svg': 1.34,
  '/assets/logos/clients-marquee/LOGO Protección.svg': 1.52,
  '/assets/logos/clients-marquee/LOGO Seguros del Estado.svg': 1.22,
  '/assets/logos/clients-marquee/LOGO Bupa.svg': 1.38,
  '/assets/logos/clients-marquee/LOGO Bienestar Familiar.svg': 1.42,
  '/assets/logos/clients-marquee/LOGO Cafam.svg': 1.26,
  '/assets/logos/clients-marquee/LOGO Cencosud.svg': 1.22,
  '/assets/logos/clients-marquee/LOGO Tuya.svg': 1.18,
  '/assets/logos/clients-marquee/LOGO UDP.svg': 1.18,
  '/assets/logos/clients-marquee/LOGO Vélez.svg': 1.22,
  '/assets/logos/clients-marquee/LOGO Western Union.svg': 1.56,
  '/assets/logos/clients-marquee/LOGO XM.svg': 1.2,
  '/assets/logos/clients-marquee/LOGO cmpc.svg': 1.32,
  '/assets/logos/clients-marquee/LOGO concha y toro.svg': 1.3,
  '/assets/logos/clients-marquee/LOGO Bci.svg': 1.12,
  '/assets/logos/clients-marquee/LOGO Besalco.svg': 1.14,
  '/assets/logos/clients-marquee/LOGO Banmédica.svg': 1.1,
  '/assets/logos/clients-marquee/LOGO Banistmo.svg': 1.08,
  '/assets/logos/clients-marquee/LOGO Celsia.svg': 1.12,
  '/assets/logos/clients-marquee/LOGO Chilexpress.svg': 1.08,
};

function humanizeLogoName(path: string) {
  return path
    .split('/')
    .pop()
    ?.replace(/\.svg$/i, '')
    .replace(/[_+]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim() || path;
}

export const clientLogosMarqueeItems: ClientLogoMarqueeItem[] = clientLogosMarquee.map((logo) => ({
  name: humanizeLogoName(logo),
  logo,
  scale: whitespaceHeavyLogoScale[logo] ?? 1,
}));
