ALTER TABLE case_studies
  ADD COLUMN IF NOT EXISTS public_title_es TEXT,
  ADD COLUMN IF NOT EXISTS public_title_en TEXT,
  ADD COLUMN IF NOT EXISTS region_es TEXT,
  ADD COLUMN IF NOT EXISTS region_en TEXT,
  ADD COLUMN IF NOT EXISTS solution_type_es TEXT,
  ADD COLUMN IF NOT EXISTS solution_type_en TEXT,
  ADD COLUMN IF NOT EXISTS objective_es TEXT,
  ADD COLUMN IF NOT EXISTS objective_en TEXT,
  ADD COLUMN IF NOT EXISTS business_pains_es TEXT[],
  ADD COLUMN IF NOT EXISTS business_pains_en TEXT[],
  ADD COLUMN IF NOT EXISTS solution_description_es TEXT,
  ADD COLUMN IF NOT EXISTS solution_description_en TEXT,
  ADD COLUMN IF NOT EXISTS capabilities_public_es TEXT[],
  ADD COLUMN IF NOT EXISTS capabilities_public_en TEXT[],
  ADD COLUMN IF NOT EXISTS quantitative_impacts_es TEXT[],
  ADD COLUMN IF NOT EXISTS quantitative_impacts_en TEXT[],
  ADD COLUMN IF NOT EXISTS qualitative_impacts_es TEXT[],
  ADD COLUMN IF NOT EXISTS qualitative_impacts_en TEXT[],
  ADD COLUMN IF NOT EXISTS metrics_text_es TEXT,
  ADD COLUMN IF NOT EXISTS metrics_text_en TEXT,
  ADD COLUMN IF NOT EXISTS additional_opportunities_es TEXT,
  ADD COLUMN IF NOT EXISTS additional_opportunities_en TEXT,
  ADD COLUMN IF NOT EXISTS public_client_name_es TEXT,
  ADD COLUMN IF NOT EXISTS public_client_name_en TEXT,
  ADD COLUMN IF NOT EXISTS show_client_identity BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS testimonial_es TEXT,
  ADD COLUMN IF NOT EXISTS testimonial_en TEXT,
  ADD COLUMN IF NOT EXISTS show_testimonial BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS gallery_images TEXT[],
  ADD COLUMN IF NOT EXISTS technology_icons TEXT[];
